import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import React from "react";

export const metadata: Metadata = {
	title: "Home - Dashboard BOAI",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="min-h-screen flex">
			<Sidebar />
			<main className="flex-1 p-6 ml-48">{children}</main>
		</div>
	);
}
